package com.runproof.rpf10;

import jakarta.annotation.PostConstruct;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;

/** Explicit, tiny PostgreSQL migration for the investigation candidate. */
@Component
public class PersistenceSchema {

    public static final String SCHEMA_VERSION = "rpf-10-postgresql-metadata-schema-v1";

    private final JdbcTemplate jdbcTemplate;
    private final DataSource dataSource;
    private volatile boolean ready;
    private volatile DatabaseIdentity databaseIdentity = DatabaseIdentity.unknown();

    public PersistenceSchema(JdbcTemplate jdbcTemplate, DataSource dataSource) {
        this.jdbcTemplate = jdbcTemplate;
        this.dataSource = dataSource;
    }

    @PostConstruct
    public void migrate() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS rpf_schema_history (
                    version VARCHAR(128) PRIMARY KEY,
                    applied_at TIMESTAMPTZ NOT NULL
                )
                """);

        List<String> versions = jdbcTemplate.query(
                "SELECT version FROM rpf_schema_history ORDER BY version",
                (rs, rowNum) -> rs.getString("version")
        );
        if (versions.stream().anyMatch(version -> !SCHEMA_VERSION.equals(version))) {
            throw new IllegalStateException("Unsupported RPF schema history; startup is blocked.");
        }

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS canonical_metadata (
                    entity_type VARCHAR(64) NOT NULL,
                    entity_id VARCHAR(256) NOT NULL,
                    outcome VARCHAR(64) NOT NULL,
                    agent_version VARCHAR(256),
                    evaluation_id VARCHAR(256),
                    supersedes_decision_id VARCHAR(256),
                    artifact_id VARCHAR(256) NOT NULL,
                    artifact_key VARCHAR(512) NOT NULL,
                    artifact_kind VARCHAR(128) NOT NULL,
                    artifact_schema_version VARCHAR(128) NOT NULL,
                    artifact_content_sha256 VARCHAR(64) NOT NULL,
                    artifact_source_sha256 VARCHAR(64) NOT NULL,
                    artifact_runtime_version VARCHAR(128) NOT NULL,
                    idempotency_key VARCHAR(512) NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL,
                    PRIMARY KEY (entity_type, entity_id),
                    CONSTRAINT canonical_metadata_idempotency_key_uk UNIQUE (idempotency_key)
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS control_plane_audit (
                    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    principal_id VARCHAR(128) NOT NULL,
                    action VARCHAR(256) NOT NULL,
                    entity_id VARCHAR(256),
                    result VARCHAR(128) NOT NULL,
                    request_id VARCHAR(128) NOT NULL,
                    occurred_at TIMESTAMPTZ NOT NULL
                )
                """);

        if (versions.isEmpty()) {
            jdbcTemplate.update(
                    "INSERT INTO rpf_schema_history(version, applied_at) VALUES (?, ?)",
                    SCHEMA_VERSION,
                    Timestamp.from(Instant.now())
            );
        }
        databaseIdentity = readDatabaseIdentity();
        ready = true;
    }

    public boolean isReady() {
        return ready;
    }

    public boolean databaseResponding() {
        try {
            Integer result = jdbcTemplate.queryForObject("SELECT 1", Integer.class);
            return result != null && result == 1;
        } catch (RuntimeException ignored) {
            return false;
        }
    }

    public DatabaseIdentity databaseIdentity() {
        return databaseIdentity;
    }

    private DatabaseIdentity readDatabaseIdentity() {
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData metaData = connection.getMetaData();
            String databaseName = connection.getCatalog();
            String schema = connection.getSchema();
            return new DatabaseIdentity(
                    metaData.getDatabaseProductName(),
                    metaData.getDatabaseProductVersion(),
                    metaData.getDriverName(),
                    metaData.getDriverVersion(),
                    databaseName == null ? "unknown" : databaseName,
                    schema == null ? "unknown" : schema
            );
        } catch (SQLException exception) {
            throw new IllegalStateException("Cannot inspect PostgreSQL identity.", exception);
        }
    }

    public record DatabaseIdentity(
            String product,
            String version,
            String jdbcDriver,
            String jdbcDriverVersion,
            String databaseName,
            String schema
    ) {
        static DatabaseIdentity unknown() {
            return new DatabaseIdentity("UNKNOWN", "UNKNOWN", "UNKNOWN", "UNKNOWN", "UNKNOWN", "UNKNOWN");
        }
    }
}
