package com.runproof.controlplane;

import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;

@Component
public class PersistenceSchema {

    public static final String SCHEMA_VERSION = "rpf-11-postgresql-canonical-schema-v1";

    private final JdbcTemplate jdbcTemplate;
    private final DataSource dataSource;
    private final String configuredSchemaVersion;
    private volatile boolean migrationValid;
    private volatile DatabaseIdentity databaseIdentity = DatabaseIdentity.unknown();

    public PersistenceSchema(
            JdbcTemplate jdbcTemplate,
            DataSource dataSource,
            @Value("${rpf.persistence.schema-version:" + SCHEMA_VERSION + "}") String configuredSchemaVersion
    ) {
        this.jdbcTemplate = jdbcTemplate;
        this.dataSource = dataSource;
        this.configuredSchemaVersion = configuredSchemaVersion;
    }

    @PostConstruct
    public void migrate() {
        if (!SCHEMA_VERSION.equals(configuredSchemaVersion)) {
            throw new IllegalStateException("Unsupported configured RPF schema version; startup is blocked.");
        }
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS rpf_schema_history (
                    version VARCHAR(128) PRIMARY KEY,
                    applied_at TIMESTAMPTZ NOT NULL
                )
                """);

        List<String> versions = jdbcTemplate.query(
                "SELECT version FROM rpf_schema_history ORDER BY applied_at, version",
                (rs, rowNum) -> rs.getString("version")
        );
        if (versions.stream().anyMatch(version -> !SCHEMA_VERSION.equals(version))) {
            throw new IllegalStateException("Unsupported RPF schema history; startup is blocked.");
        }

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS canonical_metadata (
                    entity_type VARCHAR(64) NOT NULL,
                    entity_id VARCHAR(256) NOT NULL,
                    entity_schema_version VARCHAR(128) NOT NULL,
                    artifact_kind VARCHAR(128) NOT NULL,
                    outcome VARCHAR(64) NOT NULL,
                    agent_version VARCHAR(256),
                    evaluation_id VARCHAR(256),
                    source_sha256 VARCHAR(64) NOT NULL,
                    runtime_version VARCHAR(256) NOT NULL,
                    summary_json JSONB NOT NULL,
                    key_refs_json JSONB NOT NULL,
                    artifact_id VARCHAR(256) NOT NULL,
                    artifact_key VARCHAR(512) NOT NULL,
                    artifact_schema_version VARCHAR(128) NOT NULL,
                    artifact_content_sha256 VARCHAR(64) NOT NULL,
                    artifact_source_sha256 VARCHAR(64) NOT NULL,
                    artifact_runtime_version VARCHAR(256) NOT NULL,
                    idempotency_key VARCHAR(512) NOT NULL,
                    supersedes_entity_id VARCHAR(256),
                    registered_by VARCHAR(128) NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL,
                    PRIMARY KEY (entity_type, entity_id),
                    CONSTRAINT canonical_metadata_idempotency_key_uk UNIQUE (idempotency_key)
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS control_plane_audit (
                    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    principal_id VARCHAR(128) NOT NULL,
                    action VARCHAR(256) NOT NULL,
                    entity_type VARCHAR(64),
                    entity_id VARCHAR(256),
                    result VARCHAR(128) NOT NULL,
                    request_id VARCHAR(128) NOT NULL,
                    reason_code VARCHAR(128),
                    occurred_at TIMESTAMPTZ NOT NULL
                )
                """);

        if (versions.isEmpty()) {
            jdbcTemplate.update(
                    "INSERT INTO rpf_schema_history(version, applied_at) VALUES (?, ?)",
                    SCHEMA_VERSION,
                    Timestamp.from(Instant.now())
            );
        }
        databaseIdentity = readDatabaseIdentity();
        migrationValid = true;
    }

    public boolean isMigrationValid() {
        return migrationValid;
    }

    public boolean databaseResponding() {
        if (!migrationValid) return false;
        try {
            Integer result = jdbcTemplate.queryForObject("SELECT 1", Integer.class);
            return result != null && result == 1;
        } catch (RuntimeException ignored) {
            return false;
        }
    }

    public DatabaseIdentity databaseIdentity() {
        return databaseIdentity;
    }

    private DatabaseIdentity readDatabaseIdentity() {
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData metadata = connection.getMetaData();
            return new DatabaseIdentity(
                    metadata.getDatabaseProductName(),
                    metadata.getDatabaseProductVersion(),
                    metadata.getDriverName(),
                    metadata.getDriverVersion(),
                    connection.getCatalog() == null ? "unknown" : connection.getCatalog(),
                    connection.getSchema() == null ? "unknown" : connection.getSchema()
            );
        } catch (SQLException exception) {
            throw new IllegalStateException("Cannot inspect PostgreSQL identity.", exception);
        }
    }

    public record DatabaseIdentity(
            String product,
            String version,
            String jdbcDriver,
            String jdbcDriverVersion,
            String databaseName,
            String schema
    ) {
        static DatabaseIdentity unknown() {
            return new DatabaseIdentity("UNKNOWN", "UNKNOWN", "UNKNOWN", "UNKNOWN", "UNKNOWN", "UNKNOWN");
        }
    }
}
